### PR TITLE
feat: add user change password functionality to backend #21

### PR DESCRIPTION
**Pull request by mucoban**
Change password functionality on backend has been created

- new endpoint created "/change-password"
- check for authentication token
- check for passwordCurrent, passwordNew params
- validation for passwordNew to be min 8 char length, contain a number, special charater, capital & small case
- postman json attached
[real-estate.postman_collection.json](https://github.com/eevan7a9/real-estate-management/files/14621384/real-estate.postman_collection.json)

### CODE REVIEW

**Comment by mucoban** [comment]
hi @eevan7a9 , can you review the pr

**Review by eevan7a9 — APPROVED** [review]
I've reviewed your pull request and everything looks great

**Comment by eevan7a9** [comment]
@mucoban thanks for the Great PR

**Comment by mucoban** [comment]
@eevan7a9 you are very welcome. I am glad you are okay with it :)

**Pull request merged**
